### ISSUE TITLE
Make a policy about policies formating

### ISSUE THREAD

**Issue by clesaege** [kleros/policies#1]
Make a policy about the formatting of others policies.
You can also give an example policy ("no assassination market" is a good start as it will be really non controversial one (at least I hope 😆)).

**Comment by proftomwbell** [comment]
You could start with at least a safe harbor:  "If a party could have the same claim decided by any government court of a member nation of the U.N., it can be heard by a Kleros court."

**Comment by bionexus** [comment]
Actually, the policy is already done.
